### PR TITLE
Example for Teams and Users permissions

### PR DESCRIPTION
**Pull request by josx**
- kill whitespaces
- add teams to aor
- add sample authorization in aor
- Hook on authentication for adding a custom prop to JWT payload

After this, we still need to know how to send current logged user data on the payload.

### CODE REVIEW

**Comment by kfern** [comment]
Perfect!! Thank you. Next week i'll test and merge.

Users model needs a role field?

**Comment by josx** [comment]
anyways permission could be anything you want, not just a role.

**Comment by kfern** [comment]
@josx Thank you!! I'm going to complete it

**Comment by josx** [comment]
great!

**Pull request merged**
